### ISSUE TITLE
Parsing input file endings

### ISSUE THREAD

**Issue by qinqin-yu** [leosanbu/pyngoST#2]
Hi Leonor,

I noticed that there may be a small typo in checking that the input filenames end in .fasta, .fas, .fa, .fna in the file `pyngoST_utils.py` line 665. I believe there should be parentheses so that any of the file endings are accepted (rather than only .fasta):  

`if not (fpath.endswith('.fasta') or fpath.endswith('.fas') or fpath.endswith('.fa') or fpath.endswith('.fna')):
`

Thank you!
QinQin

**Comment by leosanbu** [comment]
Thanks very much QinQin :) This is now updated.

**Comment by tatumdmortimer** [comment]
Hi Leo! FYI, I think the version installed via pip still has this typo.

**Comment by leosanbu** [comment]
Hii Tatum,
You're right, apologies! I updated this on Github but not Pypi. I'll revise a couple other things and upload the new version as soon as I can.

Best,
Leo
